[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "gpt-telegram-bot"
version = "1.0.0"
authors = [
    {name = "Your Name"}
]
description = "GPT Telegram Bot"
requires-python = ">=3.11"

[tool.setuptools]
package-dir = {"" = "src"}